"""Move to Base class

Revision ID: 2946096eca57
Revises: e70c62381b2f
Create Date: 2026-02-19 14:10:25.825640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2946096eca57'
down_revision = 'e70c62381b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
